/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easyb.s.Views;

import com.sun.glass.events.KeyEvent;
import easyb.s.Users.Buyer;
import easyb.s.Global;
import easyb.s.Users.Seller;
import easyb.s.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Steve
 */
public class CreateAccountView extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
    public CreateAccountView() {
        initComponents();
        checkTypeUser();

    }

    //This method checks that the user to be created is either a buyyer or a seller. 
    //If the user is a seller a new TextField is allowed so that it can type inside it.
    public void checkTypeUser() {

        String typeUser = selectUserComboBox.getSelectedItem().toString();

        if (typeUser.equals("Buyer")) {

            commercialReasonTextField.setEditable(false);

        } else {

            commercialReasonTextField.setEditable(true);

        }

    }

    //This method cleans the TextFields.
    public void cleanTextFields() {

        commercialReasonTextField.setText("");
        fullNameTextField.setText("");
        idTextField.setText("");
        ageTextField.setText("");
        emailTextField.setText("");
        countryTextField.setText("");
        passWordTextField.setText("");
        selectUserComboBox.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fullNameTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        commercialReasonTextField = new javax.swing.JTextField();
        createAccountButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        selectUserComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        passWordTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Full Name or Social Reason ");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("ID or Company Registration Number");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Age");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("eMail");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Country of Origin");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("Commercial Reason");

        jLabel9.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        jLabel9.setText("Create Account");

        fullNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fullNameTextFieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fullNameTextFieldKeyPressed(evt);
            }
        });

        idTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTextFieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTextFieldKeyPressed(evt);
            }
        });

        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });
        ageTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageTextFieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageTextFieldKeyPressed(evt);
            }
        });

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        emailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailTextFieldKeyPressed(evt);
            }
        });

        countryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryTextFieldActionPerformed(evt);
            }
        });
        countryTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                countryTextFieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                countryTextFieldKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("***Only for Commercial Establishments***");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        commercialReasonTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commercialReasonTextFieldActionPerformed(evt);
            }
        });
        commercialReasonTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                commercialReasonTextFieldKeyPressed(evt);
            }
        });

        createAccountButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        createAccountButton.setText("Create your EasyB&S account");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel11.setText("Select the type of user");

        selectUserComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buyer", "Seller" }));
        selectUserComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectUserComboBoxActionPerformed(evt);
            }
        });
        selectUserComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                selectUserComboBoxKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setText("PassWord");

        passWordTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passWordTextFieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passWordTextFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(selectUserComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(countryTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageTextField)
                                    .addComponent(idTextField)
                                    .addComponent(fullNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel1)))
                                        .addGap(0, 3, Short.MAX_VALUE)))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(commercialReasonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 3, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel11)))
                                    .addComponent(passWordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commercialReasonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectUserComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passWordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(createAccountButton)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void countryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryTextFieldActionPerformed

    private void commercialReasonTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commercialReasonTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commercialReasonTextFieldActionPerformed

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        //When this button is clicked, the system proceeds to confirm if the electronic 
        //mail that is being used to create the new account is already registered in an 
        //already made account, if this happens the system notifies the new user that the 
        //mail is already in use. If the email is not in use, the system will save the new 
        //user to the system.

        if (fullNameTextField.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "You must define a NAME to create an account",
                    "Problem creating user account", JOptionPane.ERROR_MESSAGE);
            this.fullNameTextField.requestFocus();
            return;
            
        }
        
        if (idTextField.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "You must define an ID to create an account",
                    "Problem creating user account", JOptionPane.ERROR_MESSAGE);
            this.idTextField.requestFocus();
            return;
            
        }
        
        if (ageTextField.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "You must define an AGE to create an account",
                    "Problem creating user account", JOptionPane.ERROR_MESSAGE);
            this.ageTextField.requestFocus();
            return;
            
        }
        
        if (emailTextField.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "You must define an EMAIL to create an account",
                    "Problem creating user account", JOptionPane.ERROR_MESSAGE);
            this.emailTextField.requestFocus();
            return;
            
        }
        
        if (countryTextField.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "You must define a COUNTRY to create an account",
                    "Problem creating user account", JOptionPane.ERROR_MESSAGE);
            this.countryTextField.requestFocus();
            return;
            
        }
        
        if (passWordTextField.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "You must define a PASSWORD to create an account",
                    "Problem creating user account", JOptionPane.ERROR_MESSAGE);
            this.passWordTextField.requestFocus();
            return;
            
        }

        String typeUser = selectUserComboBox.getSelectedItem().toString();
        
        for (User emailUser : Global.usersList){
            
            String email = emailUser.getEmail();
            if (email.equals(emailTextField.getText())){
                
                JOptionPane.showMessageDialog(this, "The email " + emailTextField.getText() + 
                        " is already used in another account",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }  
            
        }

        if (typeUser.equals("Buyer")) {

            String name = fullNameTextField.getText();
            int id = Integer.parseInt(idTextField.getText());
            int age = Integer.parseInt(ageTextField.getText());
            String email = emailTextField.getText();
            String country = countryTextField.getText();
            String passWord = passWordTextField.getText();

            Buyer newBuyer = new Buyer(name, id, age, email, country, typeUser, passWord);
            Global.usersList.add(newBuyer);

            cleanTextFields();
            
            System.out.println("The size of the user list is: " + Global.usersList.size());
            
            System.out.println("You created an account on EasyB&S this date: ");
            newBuyer.getShowTime();

            System.out.println(newBuyer.getInformation() + "\n" + "* ** *** **** | **** *** ** *");

        } else {

            String commercialReason = commercialReasonTextField.getText();
            String name = fullNameTextField.getText();
            int id = Integer.parseInt(idTextField.getText());
            int age = Integer.parseInt(ageTextField.getText());
            String email = emailTextField.getText();
            String country = countryTextField.getText();
            String passWord = passWordTextField.getText();

            Seller newSeller = new Seller(commercialReason, name, id, age, email, country, typeUser, passWord);
            Global.usersList.add(newSeller);
            
            cleanTextFields();
            
            System.out.println("The size of the user list is: " + Global.usersList.size());

            System.out.println("You created an account on EasyB&S this date: ");
            newSeller.getShowTime();
            
            System.out.println(newSeller.getInformation() + "\n" + "* ** *** **** | **** *** ** *");

        }

       this.dispose();
    
    }//GEN-LAST:event_createAccountButtonActionPerformed

    private void selectUserComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectUserComboBoxActionPerformed
        // TODO add your handling code here:

        checkTypeUser();

    }//GEN-LAST:event_selectUserComboBoxActionPerformed

    private void fullNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fullNameTextFieldKeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')  && (c == 8)) {
            evt.consume();
        }
  
    }//GEN-LAST:event_fullNameTextFieldKeyTyped

    private void countryTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_countryTextFieldKeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        int e = evt.getKeyCode();

        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c == 8)) {
            evt.consume();
        }

    }//GEN-LAST:event_countryTextFieldKeyTyped

    private void idTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextFieldKeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_idTextFieldKeyTyped

    private void ageTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTextFieldKeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_ageTextFieldKeyTyped

    private void passWordTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passWordTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_passWordTextFieldKeyTyped

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldActionPerformed

    private void fullNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fullNameTextFieldKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            this.idTextField.requestFocus();
            
        }
        
    }//GEN-LAST:event_fullNameTextFieldKeyPressed

    private void idTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextFieldKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            this.ageTextField.requestFocus();
            
        }
        
    }//GEN-LAST:event_idTextFieldKeyPressed

    private void ageTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTextFieldKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            this.emailTextField.requestFocus();
            
        }
        
    }//GEN-LAST:event_ageTextFieldKeyPressed

    private void countryTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_countryTextFieldKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            this.selectUserComboBox.requestFocus();
            
        }
        
    }//GEN-LAST:event_countryTextFieldKeyPressed

    private void commercialReasonTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_commercialReasonTextFieldKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            this.createAccountButton.requestFocus();
            
        }
    }//GEN-LAST:event_commercialReasonTextFieldKeyPressed

    private void emailTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextFieldKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            this.countryTextField.requestFocus();
            
        }
        
    }//GEN-LAST:event_emailTextFieldKeyPressed

    private void selectUserComboBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_selectUserComboBoxKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            this.passWordTextField.requestFocus();
            
        }
    }//GEN-LAST:event_selectUserComboBoxKeyPressed

    private void passWordTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passWordTextFieldKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            this.createAccountButton.requestFocus();
            
        }
    }//GEN-LAST:event_passWordTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccountView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextField;
    private javax.swing.JTextField commercialReasonTextField;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField passWordTextField;
    private javax.swing.JComboBox<String> selectUserComboBox;
    // End of variables declaration//GEN-END:variables
}
