/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easyb.s.Views;

import easyb.s.Global;
import easyb.s.Product.NewReview;
import javax.swing.DefaultListModel;
import easyb.s.Product.ProductSold;
import easyb.s.User;
import javax.swing.JTextField;

/**
 *
 * @author Steve
 */
public class StatisticView extends javax.swing.JFrame {

    /**
     * Creates new form StatisticView
     */
    public StatisticView() {
        initComponents();
        clearReviewList();
        showReviewList();
        showTotal();
        showInfoLabel();
    }

    //This method shows the user the list of reviews that he has.
    public void showReviewList(){
        
    javax.swing.DefaultListModel model;
        
        model = new javax.swing.DefaultListModel();
        
        for (NewReview newReview : Global.reviewList) {
            
            String emailForWhom = newReview.getForWhom();
            String emailWhoMakeIt = newReview.getWhoMakeIt();
                  
                  if (emailForWhom.equals(Global.emailUser)){
            
                    model.addElement("WhoMakeIt: " + newReview.getWhoMakeIt() + " |*| " + 
                            "Wich Product: " + newReview.getProductName() + " |*| " + 
                            "Calification: " + newReview.getCalification() + " |*| " +
                            "Comment: " + newReview.getComment());
            
                  }

        reviewList.setModel(model);

    }

    }
    
    //This method cleans the Review List.
    private void clearReviewList(){
        
        DefaultListModel clearReviewList = new DefaultListModel();    
        
        clearReviewList.removeAllElements();
    
    }

    //This method shows the totals of product quantities and total money. 
    //If the user is a buyer, this method shows the amount of product purchased 
    //and the total that has paid for purchases. If the user is a seller, 
    //this method shows the amount of product sold and the total amount of money 
    //generated by the sale of these products.
    private void showTotal(){
        
      int totalQuantity = 0;
      int totalAmount = 0;
    
      for (ProductSold info : Global.soldProductList) {
                
        int amountProduct = info.getAmount();
        int priceProduct= info.getPrice();
        String emailBuyer = info.getEmailBuyer();
        String emailSeller = info.getEmailSeller();
                  
                
        if (emailBuyer.equals(Global.emailUser)){
                    
            totalQuantity = totalQuantity + amountProduct ;
            totalAmount = priceProduct + totalAmount;
                    
        }   
        
        else if (emailSeller.equals(Global.emailUser)){
            
            totalQuantity = totalQuantity + amountProduct ;
            totalAmount = priceProduct + totalAmount;
            
        }
         
        }
      
        totalQuantityTextField.setText(String.valueOf(totalQuantity));
        totalAmountTextField.setText("$" + totalAmount);
        totalQuantityTextField.setHorizontalAlignment(JTextField.RIGHT);
        totalAmountTextField.setHorizontalAlignment(JTextField.RIGHT);
   
    }
    
    
    //This method shows some information in the Labels. If the user is a buyer, 
    //the labels show information such as "Total Purchases" and "Total Paid". 
    //If the user is a seller, the labels show information such as "Total Sales" 
    //and "Total Received".
    private void showInfoLabel(){
        
        for (int i = 0; Global.usersList.size() > i; i++){
            
                User position = Global.usersList.get(i);
                
                if ((position.getEmail().equals(Global.emailUser))){
                    
                    if (position.getUser().equals("Buyer")){
                       
                        totalQuantityLabel.setText("Total Purchases: ");
                        totalAmountLabel.setText("Total Paid: ");
  
                    }else{
                        
                        totalQuantityLabel.setText("Total Sales: ");
                        totalAmountLabel.setText("Total Received: ");
                      
                    }
                }
        }
        
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reviewList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        totalQuantityLabel = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        totalQuantityTextField = new javax.swing.JTextField();
        totalAmountTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        reviewList.setBackground(new java.awt.Color(240, 240, 255));
        reviewList.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jScrollPane1.setViewportView(reviewList);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("List Of Reviews");

        totalQuantityLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        totalQuantityLabel.setText("Total Quantity:");

        totalAmountLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        totalAmountLabel.setText("Total Amount:");

        totalQuantityTextField.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        totalQuantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalQuantityTextFieldActionPerformed(evt);
            }
        });

        totalAmountTextField.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalQuantityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(totalAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(totalQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalQuantityLabel)
                    .addComponent(totalQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalAmountLabel)
                    .addComponent(totalAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalQuantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalQuantityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalQuantityTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> reviewList;
    private javax.swing.JLabel totalAmountLabel;
    private javax.swing.JTextField totalAmountTextField;
    private javax.swing.JLabel totalQuantityLabel;
    private javax.swing.JTextField totalQuantityTextField;
    // End of variables declaration//GEN-END:variables
}
